AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/Documentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false